sonar.projectKey=GScandelari_curva_mestra_system
sonar.projectName=Curva Mestra System
sonar.organization=gscandelari

# Source code location
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.spec.ts

# Coverage
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Language
sonar.language=ts
